# Generated by Django 2.2.5 on 2019-09-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
