# Generated by Django 2.2.5 on 2019-09-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='text',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
