# Generated by Django 2.2.5 on 2019-09-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Step',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='name',
            new_name='step_text',
        ),
    ]
