# Generated by Django 2.2.5 on 2019-09-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20190923_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='step',
            name='step_text',
            field=models.CharField(max_length=200),
        ),
    ]
